// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwrmkqihdxkpkiewxhec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cm1rcWloZHhrcGtpZXd4aGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTA2NzcsImV4cCI6MjA1OTc4NjY3N30.wEdqNMzAro9L-ZYQyAwIYnPGdP682wndJjJwP10n68o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);